siteTitle = "Rebecca Goss - UX Designer"
siteAuthor = "Rebecca Goss"
siteDescription = "I&rsquo;m Rebecca and I&rsquo;m a <span className='ttl small-caps'>UX</span> designer based in London, United Kingdom."
siteMetaDescription = "I'm Rebecca and I'm a UX designer based in London, United Kingdom."
siteImage = "http://www.rebeccagoss.co.uk/fake-shoulder-bw.jpg"
siteURL = "http://www.rebeccagoss.co.uk/"

googleAnalyticsId = "UA-91320747-1"

linkPrefix = "http://www.rebeccagoss.co.uk/"
