siteTitle = "Rebecca Goss - UX Designer"
siteAuthor = "Rebecca Goss"
siteDescription = "I'm Rebecca and I&rsquo;m a <span className='ttl small-caps'>UX</span> designer based in London, United Kingdom."

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = "UA-91320747-1"

linkPrefix = "/"
